let cadena = "Cadena de prueba";
let cadena2 = "Cadena 2";

// resultado = cadena.concat(" Hola");
// resultado = cadena.concat(cadena2);
/* resultado = cadena.startsWith(cadena2);      si una cadena comienza con los caracteres de otra cadena, devuelve true, sino devuelve false (si la cadena comienza por los caracteres de la cadena2)*/
// resultado = cadena.endsWith(cadena2);        si una cadena termina con los caracteres de otra cadena, devuelve true, si no devuelve false
// resultado = cadena.includes(cadena2);        si una cadena puede encontrarse dentro de otra cadena devuelve true, si no devuelve false
// resultado = cadena.indexOf();                devuelve el indice del primer caracter de la cadena, si no existes devuelve -1                 
// resultado = cadena.lastIndexOf();            devuelve el ultimo indice del primer caracter de la cadena, si no existe devuelve -1
// resultado = cadena.padStart();               rellenar cadena al principio con los caracteres deseados
// resultado = cadena.padEnd();                 rellenar cadena al final con los caracteres deseados
// resultado = cadena.repeat();                 devuelve la misma cadena pero repetida la cantidad que queremos
// resultado = cadena.split();                  divide la cadena como la pidamos
// resultado = cadena.subString();              nos retorna un pedazo de la celda que seleccionamos
// resultado = cadena.toLowerCase();            convierte una cadena en minuscula
// resultado = cadena.toUpperCase();            convierte una cadena en mayuscula 
// resultado = cadena.toString();               metodo que devuelve una cadena que representa al objeto especificado
// resultado = cadena.trim();                   elimina los espacios en blanco al principio y al final de la cadena
// resultado = cadena.trimEnd();                elimina los espacios en blanco al final de la cadena
// resultado = cadena.trimStart();              elimina los espacios en blanco al principio de la cadena
// resultado = cadena.valueOf();                retorna el valor primitivo de un objeto string